name: Docker Image CI

on:
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - '**/README.md'


env:
  REPO_NAME: telegrambot

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: bbcbear/telegrambot:latest
      
      
      
      
